name: Lint Readme
on: [pull_request, push]

jobs:
  lint_readme:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install codespell
      - run: codespell
